# Generated by Django 5.0.7 on 2024-08-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("pincode", models.CharField(max_length=6)),
                ("policy_name", models.CharField(max_length=255)),
                ("plan_type", models.CharField(max_length=255)),
                ("policy_start_date", models.DateField()),
                ("duration", models.IntegerField()),
                (
                    "premium_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
