# Generated by Django 5.0.7 on 2024-08-03 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_member_groups_member_is_active_member_is_staff_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("pincode", models.CharField(max_length=6)),
                ("policy_name", models.CharField(max_length=255)),
                ("plan_type", models.CharField(max_length=50)),
                ("policy_start_date", models.DateField()),
                ("duration", models.IntegerField()),
                (
                    "premium_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("password", models.CharField(max_length=128)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
