# Generated by Django 5.0.7 on 2024-08-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_profile_delete_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="password",
        ),
    ]
