# Generated by Django 5.0.7 on 2024-08-06 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_profile_insurer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("claim_id", models.AutoField(primary_key=True, serialize=False)),
                ("claim_date", models.DateField()),
                (
                    "amount_claimed",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("treatment_info", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
