# Generated by Django 5.1 on 2024-08-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0007_claim"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="hospital_name",
            field=models.TextField(default="none"),
            preserve_default=False,
        ),
    ]
