# Generated by Django 5.1 on 2024-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0008_claim_hospital_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="unique_id",
            field=models.CharField(
                default=123456, editable=False, max_length=6, unique=True
            ),
            preserve_default=False,
        ),
    ]
